export const UREA_TO_BUN_CONVERSION = 2.8;
export const BUN_MG_DL_THRESHOLD = 19;

export const CURB65_RESPIRATORY_RATE_THRESHOLD = 30;
export const CURB65_SYSTOLIC_BP_THRESHOLD = 90;
export const CURB65_DIASTOLIC_BP_THRESHOLD = 60;
export const CURB65_AGE_THRESHOLD = 65;

export const CENTOR_AGE_YOUNG_MIN = 3;
export const CENTOR_AGE_YOUNG_MAX = 14;
export const CENTOR_AGE_MIDDLE_MIN = 15;
export const CENTOR_AGE_MIDDLE_MAX = 44;
export const CENTOR_AGE_OLD_MIN = 45;

export const HEART_AGE_HIGH_THRESHOLD = 65;
export const HEART_AGE_MODERATE_THRESHOLD = 45;
export const HEART_RISK_FACTORS_HIGH_THRESHOLD = 3;
export const HEART_RISK_FACTORS_LOW_THRESHOLD = 1;

export const CHA2DS2_AGE_HIGH_THRESHOLD = 75;
export const CHA2DS2_AGE_MODERATE_THRESHOLD = 65;

export const QSOFA_RESPIRATORY_RATE_THRESHOLD = 22;
export const QSOFA_SYSTOLIC_BP_THRESHOLD = 100;

export const ALVARADO_TEMPERATURE_THRESHOLD = 37.3;
export const ALVARADO_WBC_THRESHOLD = 10000;
export const ALVARADO_NEUTROPHIL_THRESHOLD = 75;

export const GLASGOW_BUN_THRESHOLD_HIGH = 70;
export const GLASGOW_BUN_THRESHOLD_MEDIUM_HIGH = 28;
export const GLASGOW_BUN_THRESHOLD_MEDIUM = 22.4;
export const GLASGOW_BUN_THRESHOLD_LOW = 18.2;

export const GLASGOW_HGB_THRESHOLD_LOW = 10;
export const GLASGOW_HGB_THRESHOLD_MEDIUM_MALE = 12;
export const GLASGOW_HGB_THRESHOLD_HIGH_MALE = 13;

export const GLASGOW_BP_THRESHOLD_LOW = 90;
export const GLASGOW_BP_THRESHOLD_MEDIUM = 100;
export const GLASGOW_BP_THRESHOLD_HIGH = 110;
export const GLASGOW_PULSE_THRESHOLD = 100;

export const SOFA_PLATELET_THRESHOLD_CRITICAL = 20;
export const SOFA_PLATELET_THRESHOLD_SEVERE = 50;
export const SOFA_PLATELET_THRESHOLD_MODERATE = 100;
export const SOFA_PLATELET_THRESHOLD_MILD = 150;

export const SOFA_BILIRUBIN_THRESHOLD_CRITICAL = 12;
export const SOFA_BILIRUBIN_THRESHOLD_SEVERE = 6;
export const SOFA_BILIRUBIN_THRESHOLD_MODERATE = 2;
export const SOFA_BILIRUBIN_THRESHOLD_MILD = 1.2;

export const SOFA_MAP_THRESHOLD = 70;
export const SOFA_GCS_THRESHOLD_CRITICAL = 6;
export const SOFA_GCS_THRESHOLD_SEVERE = 10;
export const SOFA_GCS_THRESHOLD_MODERATE = 13;
export const SOFA_GCS_THRESHOLD_MILD = 15;

export const SOFA_CREATININE_THRESHOLD_CRITICAL = 5;
export const SOFA_CREATININE_THRESHOLD_SEVERE = 3.5;
export const SOFA_CREATININE_THRESHOLD_MODERATE = 2;
export const SOFA_CREATININE_THRESHOLD_MILD = 1.2;
export const SOFA_URINE_OUTPUT_THRESHOLD_CRITICAL = 200;
export const SOFA_URINE_OUTPUT_THRESHOLD_SEVERE = 500;

export const SOFA_PAO2_FIO2_THRESHOLD_CRITICAL = 100;
export const SOFA_PAO2_FIO2_THRESHOLD_SEVERE = 200;
export const SOFA_PAO2_FIO2_THRESHOLD_MODERATE = 300;
export const SOFA_PAO2_FIO2_THRESHOLD_MILD = 400;

export const PERC_AGE_THRESHOLD = 50;
export const PERC_HEART_RATE_THRESHOLD = 100;
export const PERC_O2_SAT_THRESHOLD = 95;

export const TIMI_AGE_THRESHOLD = 65;
export const TIMI_RISK_FACTORS_THRESHOLD = 3;

export const MELD_MIN_LAB_VALUE = 1;
export const MELD_MAX_CREATININE = 4;
export const MELD_MIN_SCORE = 6;
export const MELD_MAX_SCORE = 40;
export const MELD_BILIRUBIN_COEFFICIENT = 3.78;
export const MELD_INR_COEFFICIENT = 11.2;
export const MELD_CREATININE_COEFFICIENT = 9.57;
export const MELD_CONSTANT = 6.43;

export const HAS_BLED_AGE_THRESHOLD = 65;
