export const CLINICAL_GUIDANCE = {
  curb65: [
    { threshold: 2, guidance: { riskCategory: 'Low Risk', interpretation: 'Low risk of mortality (1.5% for score 0, 3.2% for score 1)', recommendation: 'Consider outpatient treatment. Patients can typically be managed at home with oral antibiotics if pneumonia is confirmed.' } },
    { threshold: 3, guidance: { riskCategory: 'Moderate Risk', interpretation: 'Moderate risk of mortality (13%)', recommendation: 'Consider hospital admission or close outpatient monitoring. Short inpatient observation may be appropriate.' } },
    { threshold: 6, guidance: { riskCategory: 'High Risk', interpretation: (score: number) => `High risk of mortality (${score === 3 ? '17%' : score === 4 ? '41.5%' : '57%'})`, recommendation: 'Hospital admission recommended. Consider ICU admission for scores 4-5, especially with additional risk factors.' } },
  ] as { threshold: number; guidance: { riskCategory: string; interpretation: string | ((score: number) => string); recommendation: string } }[],
  centor: [
    { threshold: 2, guidance: { riskCategory: 'Very Low Risk', interpretation: (score: number) => `${score <= 0 ? '1-2.5%' : '5-10%'} probability of streptococcal pharyngitis`, recommendation: 'No testing or antibiotics needed. Symptomatic treatment is appropriate. Streptococcal infection is unlikely.' } },
    { threshold: 4, guidance: { riskCategory: 'Moderate Risk', interpretation: (score: number) => `${score === 2 ? '11-17%' : '28-35%'} probability of streptococcal pharyngitis`, recommendation: 'Rapid antigen detection test (RADT) or throat culture recommended. Treat with antibiotics if test is positive.' } },
    { threshold: 5, guidance: { riskCategory: 'High Risk', interpretation: '51-53% probability of streptococcal pharyngitis', recommendation: 'Consider empiric antibiotic treatment or perform rapid antigen detection test. High likelihood of streptococcal infection.' } },
  ] as { threshold: number; guidance: { riskCategory: string; interpretation: string | ((score: number) => string); recommendation: string } }[],
  wells_dvt: [
    { threshold: 1, guidance: { riskCategory: 'Low Probability', interpretation: 'Low probability of DVT (~5%)', recommendation: 'D-dimer testing recommended. If D-dimer is negative, DVT is effectively ruled out. If positive, proceed to ultrasound imaging.' } },
    { threshold: 3, guidance: { riskCategory: 'Moderate Probability', interpretation: 'Moderate probability of DVT (~17%)', recommendation: 'D-dimer testing recommended. If negative, DVT unlikely. If positive, compression ultrasound is indicated.' } },
    { threshold: 10, guidance: { riskCategory: 'High Probability', interpretation: 'High probability of DVT (~53%)', recommendation: 'Compression ultrasound imaging strongly recommended. Consider empiric anticoagulation while awaiting imaging if no contraindications.' } },
  ],
  wells_pe: [
    { threshold: 2, guidance: { riskCategory: 'Low Probability', interpretation: 'Low probability of PE (~2%)', recommendation: 'D-dimer testing recommended. If D-dimer is negative, PE is effectively ruled out. If positive, proceed to CT pulmonary angiography (CTPA).' } },
    { threshold: 6.5, guidance: { riskCategory: 'Moderate Probability', interpretation: 'Moderate probability of PE (~20-30%)', recommendation: 'D-dimer or CTPA recommended depending on clinical judgment. If D-dimer positive or not performed, CTPA is indicated.' } },
    { threshold: 13, guidance: { riskCategory: 'High Probability', interpretation: 'High probability of PE (~65%)', recommendation: 'CT pulmonary angiography (CTPA) strongly recommended. Consider empiric anticoagulation if no contraindications while awaiting imaging.' } },
  ],
  heart: [
    { threshold: 4, guidance: { riskCategory: 'Low Risk', interpretation: 'Low risk of major adverse cardiac events (MACE) at 6 weeks: 0.9-1.7%', recommendation: 'Early discharge with outpatient follow-up is appropriate. No further cardiac workup needed unless clinically indicated. Consider non-cardiac causes of chest pain.' } },
    { threshold: 7, guidance: { riskCategory: 'Moderate Risk', interpretation: 'Moderate risk of MACE at 6 weeks: 12-17%', recommendation: 'Observation with serial troponins and ECGs recommended. Stress testing or coronary CT angiography may be appropriate. Cardiology consultation should be considered.' } },
    { threshold: 11, guidance: { riskCategory: 'High Risk', interpretation: 'High risk of MACE at 6 weeks: 50-65%', recommendation: 'Urgent cardiology consultation recommended. Early invasive strategy with coronary angiography should be strongly considered. Admit for continuous monitoring and treatment.' } },
  ],
  cha2ds2_vasc: [
    { threshold: 1, guidance: { riskCategory: 'Very Low Risk', interpretation: 'Very low stroke risk (0-0.2% per year)', recommendation: 'No antithrombotic therapy recommended. Annual reassessment of stroke risk factors is advised.' } },
    { threshold: 2, guidance: { riskCategory: 'Low Risk', interpretation: 'Low stroke risk (0.6-1.3% per year)', recommendation: (score: number, sex?: string) => sex === 'female' && score === 1 ? 'For females with score of 1 (sex alone), no anticoagulation needed. For males with score of 1, consider oral anticoagulation or aspirin based on patient preferences and bleeding risk.' : 'Consider oral anticoagulation or aspirin. Discuss risks and benefits with patient. Assess bleeding risk using HAS-BLED score.' } },
    { threshold: 3, guidance: { riskCategory: 'Low-Moderate Risk', interpretation: 'Low-moderate stroke risk (2.2% per year)', recommendation: 'Oral anticoagulation recommended (direct oral anticoagulant or warfarin). Assess bleeding risk using HAS-BLED score. Benefits typically outweigh risks.' } },
    { threshold: 5, guidance: { riskCategory: 'Moderate Risk', interpretation: (score: number) => `Moderate stroke risk (${score === 3 ? '3.2%' : '4.8%'} per year)`, recommendation: 'Oral anticoagulation strongly recommended unless contraindicated. Direct oral anticoagulants (DOACs) are generally preferred over warfarin. Assess bleeding risk using HAS-BLED score.' } },
    { threshold: 7, guidance: { riskCategory: 'Moderate-High Risk', interpretation: (score: number) => `Moderate-high stroke risk (${score === 5 ? '6.7%' : '10%'} per year)`, recommendation: 'Oral anticoagulation strongly recommended. DOACs preferred over warfarin in most cases. Careful monitoring and bleeding risk assessment essential.' } },
    { threshold: 10, guidance: { riskCategory: 'High Risk', interpretation: 'High stroke risk (>10% per year)', recommendation: 'Oral anticoagulation essential unless absolute contraindication exists. DOACs preferred. Consider specialist referral for anticoagulation management and close monitoring.' } },
  ] as { threshold: number; guidance: { riskCategory: string; interpretation: string | ((score: number, sex?: string) => string); recommendation: string | ((score: number, sex?: string) => string) } }[],
  // NOTE: getRiskGuidance does first-match on `score < threshold`, which assumes
  // higher score = higher risk. GCS is inverted (lower score = worse), so the
  // thresholds are ordered ascending to catch the LOW (severe) scores first:
  //   score < 9  -> Severe   (GCS 3-8)
  //   score < 13 -> Moderate (GCS 9-12)
  //   score < 16 -> Mild     (GCS 13-15)
  gcs: [
    { threshold: 9, guidance: { riskCategory: 'Severe', interpretation: (score: number) => `Severe impairment (GCS 3-8). Critical neurological dysfunction. ${score === 3 ? 'GCS 3 is the lowest possible score indicating deep coma.' : ''}`, recommendation: 'Severe head injury. Immediate ICU admission required. Definitive airway management (intubation) strongly recommended for GCS ≤8. Emergency CT imaging and neurosurgical consultation essential. Consider ICP monitoring.' } },
    { threshold: 13, guidance: { riskCategory: 'Moderate', interpretation: 'Moderate impairment (GCS 9-12). Significant neurological dysfunction present.', recommendation: 'Moderate head injury. Requires hospital admission and close monitoring. CT imaging indicated. Consider neurosurgical consultation. May require ICU admission for frequent neurological assessments.' } },
    { threshold: 16, guidance: { riskCategory: 'Mild', interpretation: 'Mild impairment (GCS 13-15). Patient is likely to have good neurological function.', recommendation: 'Mild head injury. Observe for deterioration. Most patients with GCS 13-15 can be managed with observation. Consider CT if mechanism concerning or other high-risk features present.' } },
  ] as { threshold: number; guidance: { riskCategory: string; interpretation: string | ((score: number) => string); recommendation: string } }[],
  qsofa: [
    { threshold: 2, guidance: { riskCategory: 'Low Risk', interpretation: 'Low risk of sepsis-related mortality and poor outcomes', recommendation: 'qSOFA <2 does not rule out infection or sepsis. Continue clinical assessment. If infection suspected, consider full SOFA score and lactate measurement. Monitor closely for deterioration.' } },
    { threshold: 4, guidance: { riskCategory: 'High Risk', interpretation: 'High risk of sepsis-related mortality (in-hospital mortality ~10% for qSOFA ≥2 vs ~1% for qSOFA <2)', recommendation: 'qSOFA ≥2 suggests sepsis with organ dysfunction. URGENT: Obtain lactate, blood cultures, and complete blood count. Calculate full SOFA score. Initiate sepsis bundle immediately: IV fluids, broad-spectrum antibiotics within 1 hour, and consider ICU admission. Reassess frequently.' } },
  ],
  alvarado: [
    { threshold: 5, guidance: { riskCategory: 'Low Risk', interpretation: 'Low probability of acute appendicitis (5-20% likelihood)', recommendation: 'Appendicitis unlikely. Consider alternative diagnoses. Outpatient management with close follow-up is appropriate. Discharge with return precautions. Re-evaluate if symptoms worsen or persist beyond 24-48 hours.' } },
    { threshold: 7, guidance: { riskCategory: 'Intermediate Risk', interpretation: 'Moderate probability of acute appendicitis (30-65% likelihood)', recommendation: 'Appendicitis possible. Further evaluation recommended with CT scan or ultrasound imaging. Active observation with serial abdominal exams. Consider surgical consultation. Admission for observation may be appropriate if imaging unavailable or equivocal.' } },
    { threshold: 9, guidance: { riskCategory: 'High Risk', interpretation: 'High probability of acute appendicitis (65-85% likelihood)', recommendation: 'Surgical consultation strongly recommended. CT scan or ultrasound can help confirm diagnosis and assess for complications (perforation, abscess). May proceed to surgery based on clinical judgment. NPO (nothing by mouth) and IV hydration. Consider antibiotics.' } },
    { threshold: 11, guidance: { riskCategory: 'Very High Risk', interpretation: 'Very high probability of acute appendicitis (>85% likelihood)', recommendation: 'Urgent surgical consultation required. Imaging (CT/ultrasound) recommended but should not significantly delay surgery if patient is clinically unstable. NPO, IV fluids, analgesia, and preoperative antibiotics. Appendectomy is indicated.' } },
  ],
  glasgow_blatchford: [
    { threshold: 1, guidance: { riskCategory: 'Very Low Risk', interpretation: 'Very low risk of requiring intervention. Risk of rebleeding, intervention, or mortality is <1%.', recommendation: 'Patient may be considered for early discharge and outpatient management. No endoscopy required urgently. Ensure adequate follow-up arranged. GBS of 0 has high negative predictive value for needing intervention.' } },
    { threshold: 2, guidance: { riskCategory: 'Low Risk', interpretation: 'Low risk of requiring intervention. Still consider for potential outpatient management with close follow-up.', recommendation: 'Consider early discharge with outpatient gastroenterology follow-up if clinically stable and no other concerning features. Some patients may benefit from brief observation period.' } },
    { threshold: 6, guidance: { riskCategory: 'Moderate Risk', interpretation: 'Moderate risk of requiring intervention (transfusion, endoscopy, surgery).', recommendation: 'Hospital admission recommended. Arrange upper endoscopy within 24 hours. Type and crossmatch blood. Consider proton pump inhibitor (PPI) infusion. Monitor hemoglobin serially. Gastroenterology consultation advised.' } },
    { threshold: 12, guidance: { riskCategory: 'High Risk', interpretation: 'High risk of requiring urgent intervention. Significant likelihood of need for transfusion, endoscopic or surgical intervention.', recommendation: 'Hospital admission required. Urgent upper endoscopy (within 12-24 hours). IV PPI infusion. Aggressive fluid resuscitation. Type and crossmatch 2-4 units PRBCs. Urgent gastroenterology consultation. Consider ICU admission for close monitoring. NPO status.' } },
    { threshold: 24, guidance: { riskCategory: 'Very High Risk', interpretation: 'Very high risk of mortality and need for urgent intervention. Critical upper GI bleeding.', recommendation: 'URGENT: ICU admission. Immediate gastroenterology consultation for urgent upper endoscopy. Large-bore IV access. Aggressive resuscitation with crystalloids and blood products. Transfuse to maintain Hgb >7 g/dL (>8 in cardiovascular disease). High-dose IV PPI. Consider intubation for airway protection if massive hematemesis or altered mental status. Surgery backup may be needed.' } },
  ],
  nihss: [
    { threshold: 1, guidance: { riskCategory: 'No Stroke', interpretation: 'No stroke symptoms detected. Patient appears neurologically intact.', recommendation: 'No acute stroke treatment indicated based on NIHSS alone. Consider other causes of symptoms if clinically suspected stroke. Document baseline NIHSS for future reference.' } },
    { threshold: 5, guidance: { riskCategory: 'Minor Stroke', interpretation: 'Minor stroke (NIHSS 1-4). Small neurological deficit present.', recommendation: 'Consider thrombolytic therapy if within time window and no contraindications (though benefit may be modest for very low scores). Admit to stroke unit. Imaging (CT/MRI) to rule out hemorrhage and confirm ischemia. May be candidate for IV tPA or mechanical thrombectomy based on imaging. Aspirin if not receiving tPA.' } },
    { threshold: 16, guidance: { riskCategory: 'Moderate Stroke', interpretation: 'Moderate stroke (NIHSS 5-15). Significant neurological deficit.', recommendation: 'URGENT: Candidate for thrombolytic therapy (IV tPA) if within 4.5 hours and no contraindications. Consider mechanical thrombectomy if large vessel occlusion and within time window (up to 24 hours for select patients). Immediate CT/MRI to exclude hemorrhage. Neurology and/or stroke team consultation. Admit to stroke unit or ICU. Close monitoring for neurological deterioration.' } },
    { threshold: 21, guidance: { riskCategory: 'Moderate-Severe Stroke', interpretation: 'Moderate to severe stroke (NIHSS 16-20). Major neurological impairment.', recommendation: 'URGENT: High priority for mechanical thrombectomy if large vessel occlusion identified on CT angiography (CTA). IV tPA if eligible and within time window. Immediate neurology/stroke team consultation. ICU admission for close monitoring. High risk for hemorrhagic transformation and cerebral edema. Consider intubation if airway compromise or GCS <8. Neurosurgical consultation may be needed.' } },
    { threshold: 43, guidance: { riskCategory: 'Severe Stroke', interpretation: 'Severe stroke (NIHSS ≥21). Profound neurological deficit. High mortality risk.', recommendation: 'CRITICAL: Emergent mechanical thrombectomy evaluation if large vessel occlusion present. May still benefit from IV tPA if eligible. ICU admission required. Likely need for airway protection/intubation. Risk of malignant cerebral edema is very high - neurosurgical consultation for possible decompressive hemicraniectomy. ICP monitoring may be indicated. Discuss goals of care with family. Multidisciplinary stroke team activation essential.' } },
  ],
  sofa: [
    { threshold: 2, guidance: { riskCategory: 'Low Risk', interpretation: 'Low risk of mortality (<10%)', recommendation: 'Continue standard ICU care. Monitor closely for changes in organ function. Reassess SOFA score daily. Focus on treating underlying infection or condition.' } },
    { threshold: 7, guidance: { riskCategory: 'Moderate Risk', interpretation: (score: number) => `Moderate risk of mortality (${score <= 4 ? '15-20%' : '20-40%'})`, recommendation: 'ICU-level care required. Aggressive treatment of underlying condition. Daily SOFA scoring to track progression. Consider early consultation with specialists for individual organ support (nephrology for renal dysfunction, hepatology for liver dysfunction, etc.). Ensure adequate infection source control.' } },
    { threshold: 12, guidance: { riskCategory: 'High Risk', interpretation: (score: number) => `High risk of mortality (${score <= 9 ? '40-50%' : '50-75%'})`, recommendation: 'ICU admission essential if not already admitted. Multi-organ support likely needed. Consider mechanical ventilation, renal replacement therapy (CRRT/hemodialysis), vasopressor support as indicated. Daily SOFA scoring critical. Multidisciplinary team approach. Early goals of care discussion with family may be appropriate given high mortality risk.' } },
    { threshold: 25, guidance: { riskCategory: 'Very High Risk', interpretation: 'Very high risk of mortality (>80%). Multiple organ dysfunction syndrome (MODS).', recommendation: 'CRITICAL: Maximal ICU support required. Multi-organ failure present. Mechanical ventilation, vasopressor support, and renal replacement therapy likely all needed. Consider ECMO or other advanced therapies if available and appropriate. URGENT goals of care discussion with family essential given very high mortality. Palliative care consultation may be appropriate. Continue aggressive treatment unless family opts for comfort measures.' } },
  ] as { threshold: number; guidance: { riskCategory: string; interpretation: string | ((score: number) => string); recommendation: string } }[],
  perc: [
    { threshold: 1, guidance: { riskCategory: 'PE Ruled Out', interpretation: 'PERC negative (all 8 criteria absent). Risk of PE <1%. PE is effectively ruled out.', recommendation: 'No further workup for PE needed. PERC rule successfully excludes pulmonary embolism. No D-dimer or imaging required. Consider alternative diagnoses for patient symptoms. This rule is designed to safely avoid unnecessary testing in low-risk patients.' } },
    { threshold: 9, guidance: { riskCategory: 'Further Testing Needed', interpretation: (score: number) => `PERC positive (${score} of 8 criteria present). Cannot rule out PE with PERC alone.`, recommendation: 'Proceed with PE workup. Apply Wells PE score for risk stratification. If Wells PE is low, obtain D-dimer; if D-dimer positive or Wells PE is moderate/high, proceed to CT pulmonary angiography (CTPA). PERC rule is meant for rule-out only - when positive, standard PE diagnostic algorithm should be followed.' } },
  ] as { threshold: number; guidance: { riskCategory: string; interpretation: string | ((score: number) => string); recommendation: string } }[],
  timi: [
    { threshold: 2, guidance: { riskCategory: 'Low Risk', interpretation: 'Low risk of death, MI, or urgent revascularization at 14 days (4.7%)', recommendation: 'Conservative management appropriate. Early discharge may be considered if troponins negative and patient clinically stable. Outpatient cardiology follow-up recommended. Consider stress testing prior to discharge or as outpatient. Dual antiplatelet therapy and statin recommended.' } },
    { threshold: 3, guidance: { riskCategory: 'Low-Intermediate Risk', interpretation: 'Low-intermediate risk of death, MI, or urgent revascularization at 14 days (8.3%)', recommendation: 'Hospital admission recommended. Serial troponins and ECGs. Early risk stratification with stress testing or coronary CT angiography. Consider early invasive strategy if high-risk features develop. Dual antiplatelet therapy, statin, and anticoagulation as indicated.' } },
    { threshold: 5, guidance: { riskCategory: 'Intermediate Risk', interpretation: (score: number) => `Intermediate risk of death, MI, or urgent revascularization at 14 days (${score === 3 ? '13.2%' : '19.9%'})`, recommendation: 'Hospital admission required. Early invasive strategy should be considered within 24-72 hours. Cardiology consultation recommended. Serial troponins and continuous telemetry monitoring. Dual antiplatelet therapy (aspirin + P2Y12 inhibitor), anticoagulation, high-intensity statin, and beta-blocker. Consider early coronary angiography.' } },
    { threshold: 8, guidance: { riskCategory: 'High Risk', interpretation: (score: number) => `High risk of death, MI, or urgent revascularization at 14 days (${score === 5 ? '26.2%' : score === 6 ? '40.9%' : '40.9%'})`, recommendation: 'URGENT: Early invasive strategy strongly recommended. Coronary angiography should be performed within 24 hours (or immediately if ongoing ischemia, hemodynamic instability, or electrical instability). ICU or telemetry monitoring required. Aggressive medical therapy: dual antiplatelet therapy, anticoagulation (LMWH, fondaparinux, or UFH), high-intensity statin, beta-blocker. Cardiology consultation essential. Prepare for possible PCI or CABG.' } },
  ] as { threshold: number; guidance: { riskCategory: string; interpretation: string | ((score: number) => string); recommendation: string } }[],
  meld: [
    { threshold: 10, guidance: { riskCategory: 'Low Risk', interpretation: 'Low mortality risk (1.9% 3-month mortality). Mild liver disease.', recommendation: 'Outpatient management with hepatology follow-up. Treat underlying liver disease (e.g., alcohol cessation, antiviral therapy for hepatitis, manage NASH). Monitor for complications of cirrhosis (varices, ascites, hepatic encephalopathy). Repeat MELD calculation every 3-6 months. Not a candidate for liver transplantation at this time.' } },
    { threshold: 15, guidance: { riskCategory: 'Moderate Risk', interpretation: 'Moderate mortality risk (6% 3-month mortality). Significant liver dysfunction present.', recommendation: 'Regular hepatology follow-up required. Endoscopy for variceal screening if not done recently. Monitor for ascites, encephalopathy, and coagulopathy. Address reversible factors. May consider transplant evaluation if MELD rising or recurrent decompensation events. Calculate MELD monthly to track progression.' } },
    { threshold: 20, guidance: { riskCategory: 'Moderate-High Risk', interpretation: (score: number) => `Moderate-high mortality risk (${score >= 15 && score < 20 ? '19.6%' : '19.6-52.6%'} 3-month mortality). Advanced liver disease.`, recommendation: 'Hepatology consultation required if not already established. Transplant evaluation strongly recommended. Close monitoring for complications: variceal bleeding, spontaneous bacterial peritonitis, hepatorenal syndrome, hepatic encephalopathy. Consider hospital admission if acute decompensation. Calculate MELD every 2-4 weeks. Optimize nutrition and treat complications aggressively.' } },
    { threshold: 30, guidance: { riskCategory: 'High Risk', interpretation: (score: number) => `High mortality risk (${score >= 20 && score < 25 ? '52.6%' : score >= 25 && score < 30 ? '71.3%' : '71%'} 3-month mortality). Severe end-stage liver disease.`, recommendation: 'URGENT: Hepatology and transplant surgery consultation essential. High priority for liver transplantation (MELD ≥20 typically listed). Hospital admission strongly considered if not already admitted. Aggressive management of complications. Daily monitoring of labs, mental status, and hemodynamics. Consider ICU-level care if MELD >25. Nutritional support critical. Family discussion regarding prognosis and transplant candidacy.' } },
    { threshold: 41, guidance: { riskCategory: 'Very High Risk', interpretation: 'Very high mortality risk (>80% 3-month mortality without transplant). Critical end-stage liver disease.', recommendation: 'CRITICAL: Immediate hepatology and transplant surgery consultation if not already involved. ICU admission likely required. Maximal medical management of complications. Highest priority for liver transplantation if candidate. Without transplant, mortality is extremely high. Consider mechanical liver support if available (e.g., MARS therapy). Urgent goals of care discussion with patient and family. If not transplant candidate, palliative care consultation appropriate. MELD ≥40 represents acute liver failure or severe acute-on-chronic liver failure.' } },
  ] as { threshold: number; guidance: { riskCategory: string; interpretation: string | ((score: number) => string); recommendation: string } }[],
  gad7: [
    { threshold: 5, guidance: { riskCategory: 'Minimal Anxiety', interpretation: 'Minimal or no anxiety symptoms. Score suggests no significant anxiety disorder present.', recommendation: 'No treatment indicated based on GAD-7 alone. Reassurance and routine follow-up appropriate. Consider rescreening if symptoms develop or worsen.' } },
    { threshold: 10, guidance: { riskCategory: 'Mild Anxiety', interpretation: 'Mild anxiety symptoms present. May indicate emerging anxiety disorder.', recommendation: 'Watchful waiting with follow-up in 2-4 weeks. Consider psychoeducation about anxiety management, relaxation techniques, and stress reduction strategies. Rescreening recommended. If symptoms persist or worsen, consider treatment options. Rule out medical causes (thyroid, cardiac, medication side effects).' } },
    { threshold: 15, guidance: { riskCategory: 'Moderate Anxiety', interpretation: 'Moderate anxiety symptoms. Likely meets criteria for generalized anxiety disorder (GAD) or other anxiety disorder.', recommendation: 'Treatment recommended. Options include: cognitive behavioral therapy (CBT) as first-line, or combination of CBT with medication (SSRIs/SNRIs). Screen for comorbid depression using PHQ-9. Assess for substance use. Consider referral to mental health professional. Monitor response to treatment with repeat GAD-7 in 4-8 weeks.' } },
    { threshold: 22, guidance: { riskCategory: 'Severe Anxiety', interpretation: 'Severe anxiety symptoms. Significant functional impairment likely present.', recommendation: 'Prompt treatment essential. Combination therapy (medication + psychotherapy) typically most effective. Consider SSRIs (first-line: sertraline, escitalopram) or SNRIs (venlafaxine, duloxetine). Refer to psychiatry or mental health professional. Screen for suicide risk, comorbid depression, and substance use. Short-term benzodiazepines may be considered for acute symptom relief while starting SSRI/SNRI (which takes 2-4 weeks to take effect), but avoid long-term use due to dependence risk. Close follow-up required.' } },
  ],
  grace: [
    { threshold: 109, guidance: { riskCategory: 'Low Risk', interpretation: 'Low risk of in-hospital death (mortality <1%) and death/MI at 6 months (3%)', recommendation: 'Conservative management appropriate for low-risk patients. Serial troponins and ECGs. Early risk stratification with non-invasive testing (stress test or coronary CT angiography) prior to discharge or as outpatient. Aspirin, P2Y12 inhibitor, statin, and beta-blocker as appropriate. Cardiology follow-up recommended. Consider early discharge if clinically stable and troponins negative.' } },
    { threshold: 141, guidance: { riskCategory: 'Intermediate Risk', interpretation: (score: number) => `Intermediate risk of in-hospital death (mortality 1-3%) and death/MI at 6 months (${score < 118 ? '3-8%' : '8-12%'})`, recommendation: 'Hospital admission required. Early invasive strategy should be considered within 24-72 hours if no contraindications. Cardiology consultation recommended. Serial troponins and continuous telemetry monitoring. Dual antiplatelet therapy (aspirin + P2Y12 inhibitor), anticoagulation (UFH, LMWH, fondaparinux, or bivalirudin), high-intensity statin, and beta-blocker. Consider early coronary angiography if high-risk features present.' } },
    { threshold: 400, guidance: { riskCategory: 'High Risk', interpretation: 'High risk of in-hospital death (mortality >3%) and death/MI at 6 months (>12%)', recommendation: 'URGENT: Early invasive strategy strongly recommended. Coronary angiography should be performed within 24 hours (or immediately if ongoing ischemia, hemodynamic instability, recurrent ischemia/angina, heart failure, life-threatening arrhythmias, or mechanical complications). ICU or telemetry monitoring required. Aggressive medical therapy: dual antiplatelet therapy (aspirin + potent P2Y12 inhibitor like ticagrelor or prasugrel), anticoagulation, high-intensity statin, beta-blocker. Urgent cardiology consultation essential. Prepare for possible PCI or CABG. Consider mechanical circulatory support if cardiogenic shock present.' } },
  ] as { threshold: number; guidance: { riskCategory: string; interpretation: string | ((score: number) => string); recommendation: string } }[],
  has_bled: [
    { threshold: 1, guidance: { riskCategory: 'Low Risk', interpretation: 'Low risk of major bleeding on anticoagulation (0.9-1.2% per year)', recommendation: 'Anticoagulation is relatively safe. Benefits of stroke prevention typically outweigh bleeding risk for patients with appropriate CHA2DS2-VASc scores. Continue or initiate anticoagulation as indicated. Standard monitoring and follow-up appropriate. Patient education about bleeding signs and fall prevention.' } },
    { threshold: 2, guidance: { riskCategory: 'Low-Moderate Risk', interpretation: 'Low-moderate risk of major bleeding (1.9-2.0% per year)', recommendation: 'Anticoagulation generally still appropriate if indicated by CHA2DS2-VASc score. Benefits usually outweigh risks. Address modifiable risk factors: optimize blood pressure control, avoid NSAIDs and unnecessary antiplatelet agents, counsel on alcohol reduction if applicable. Ensure stable INR monitoring if on warfarin (or consider switching to DOAC). Regular follow-up every 3-6 months.' } },
    { threshold: 3, guidance: { riskCategory: 'Moderate Risk', interpretation: 'Moderate risk of major bleeding (3.7-4.9% per year)', recommendation: 'Anticoagulation often still recommended, but requires careful consideration of risk-benefit ratio. URGENTLY address modifiable risk factors: control hypertension (target <140/90), discontinue NSAIDs and unnecessary antiplatelets if possible, reduce alcohol use, switch from warfarin to DOAC if INR labile. Consider gastric protection (PPI) if on dual antiplatelet therapy. Closer monitoring recommended (every 3 months). Fall risk assessment and prevention strategies essential. Shared decision-making with patient crucial.' } },
    { threshold: 5, guidance: { riskCategory: 'High Risk', interpretation: (score: number) => `High risk of major bleeding (${score === 4 ? '8.7%' : '12.5%'} per year)`, recommendation: 'CAUTION: Bleeding risk is substantial. Anticoagulation decision requires careful individualized assessment. Score ≥3 suggests need to investigate and correct modifiable bleeding risks. ESSENTIAL: Control hypertension aggressively, stop all NSAIDs and unnecessary antiplatelet drugs, address alcohol use, ensure stable anticoagulation (strongly consider DOAC over warfarin). Consider gastroenterology referral if GI bleeding history. Hematology consultation may be helpful. Very close monitoring required (monthly to every 3 months). Comprehensive fall prevention program. Some patients may benefit from left atrial appendage occlusion device if anticoagulation too risky but stroke risk high. Discuss risks/benefits extensively with patient.' } },
    { threshold: 10, guidance: { riskCategory: 'Very High Risk', interpretation: 'Very high risk of major bleeding (>12% per year). Anticoagulation may be contraindicated.', recommendation: 'CRITICAL: Bleeding risk is extremely high. Anticoagulation may cause more harm than benefit. Strongly consider alternative strategies: left atrial appendage closure device (Watchman) for atrial fibrillation patients with high stroke risk. If anticoagulation absolutely necessary, use lowest effective intensity, DOACs strongly preferred over warfarin. MANDATORY interventions: aggressive BP control, eliminate all modifiable risk factors, nephrology consultation if renal dysfunction, hepatology if liver disease, hematology consultation for bleeding diathesis. Very frequent monitoring (monthly). Comprehensive patient education. Consider hospice/palliative care consultation if multiple comorbidities. Document extensive shared decision-making. Some patients may be better served by aspirin alone or no antithrombotic therapy after thorough discussion.' } },
  ],
  abcd2: [
    { threshold: 4, guidance: { riskCategory: 'Low Risk', interpretation: 'Low risk of stroke after TIA (1% at 2 days, 1.2% at 7 days, 3.1% at 90 days)', recommendation: 'Outpatient management may be appropriate for select low-risk patients. Urgent neurology evaluation within 24-48 hours. Brain MRI/MRA or CT/CTA should be performed urgently (within 24 hours). Carotid imaging (ultrasound, CTA, or MRA) required. Start antiplatelet therapy (aspirin or aspirin + clopidogrel) unless contraindicated. Address vascular risk factors: blood pressure control, statin therapy, diabetes management. If carotid stenosis >50% found, urgent vascular surgery consultation. Ensure close follow-up arranged.' } },
    { threshold: 6, guidance: { riskCategory: 'Moderate Risk', interpretation: 'Moderate risk of stroke after TIA (4.1% at 2 days, 5.9% at 7 days, 9.8% at 90 days)', recommendation: 'Hospital admission recommended or urgent evaluation in specialized TIA clinic with brain and vascular imaging within 24 hours. Brain MRI with diffusion-weighted imaging (DWI) preferred over CT. Vascular imaging of head and neck (CTA, MRA, or carotid ultrasound) essential. Continuous cardiac monitoring (telemetry) for at least 24 hours to detect atrial fibrillation. Start dual antiplatelet therapy (aspirin + clopidogrel for 21 days) if ischemic stroke ruled out. Aggressive risk factor modification: statin, blood pressure control, diabetes management. If significant carotid stenosis (70-99%), urgent carotid endarterectomy (CEA) or stenting within 2 weeks. Cardiology and neurology consultation recommended.' } },
    { threshold: 8, guidance: { riskCategory: 'High Risk', interpretation: 'High risk of stroke after TIA (8.1% at 2 days, 11.7% at 7 days, 17.8% at 90 days)', recommendation: 'URGENT: Hospital admission strongly recommended. Immediate workup required. Emergent brain imaging (MRI with DWI preferred, CT if MRI unavailable) to assess for acute infarction. Urgent vascular imaging of head and neck (CTA or MRA) to evaluate for carotid stenosis, intracranial stenosis, or dissection. Cardiac monitoring (telemetry) for ≥24-48 hours. Echocardiography (TEE preferred over TTE for PFO/thrombus detection). Immediate dual antiplatelet therapy (aspirin + clopidogrel for 21 days) if hemorrhage excluded. Urgent neurology consultation. If high-grade carotid stenosis (70-99%), emergent vascular surgery consultation for CEA or stenting within 48-72 hours if possible. Intensive blood pressure management, high-intensity statin. Consider extended cardiac monitoring (30-day event monitor) if no clear etiology found. Stroke prevention clinic follow-up essential.' } },
  ],
} as const;
